import React from 'react';
import Head from 'next/head'
import Footer from './Footer';
import Header from './Header';
import Con_style from '../styles/contact.module.css';
import { Form, Input, Button, Checkbox } from 'antd';
function contact() {
    const onFinish = (values: any) => {
        console.log('Success:', values);
      };
    
      const onFinishFailed = (errorInfo: any) => {
        console.log('Failed:', errorInfo);
      };
  return (
      <>

        <Head>
          <title>Food Port</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

      <Header />

      <div className={Con_style.contact_banner}>..</div>

      <div className="container-fluid" id={Con_style.flex_container}>
        <div className="row" id={Con_style.rowss}>
            <div className="col-lg-6">
                <div className={Con_style.img_box}>
                    <img src="/img/conatct_form_img.jpg" className="img-fluid" alt="" />
                </div>
            </div>

            <div className="col-lg-6">
                <Form layout="vertical" name="basic"labelCol={{ span: 8 }}wrapperCol={{ span: 16 }}initialValues={{ remember: true }}onFinish={onFinish}
                 onFinishFailed={onFinishFailed}autoComplete="off"className={Con_style.contact_form}>
                    <ul>
                        <li>
                            <Form.Item
                            label="Username" 
                            name="username" 
                            rules={[{ required: true, message: 'Please input your username!' }]}
                            className={Con_style.inputArea}>
                            <Input className={Con_style.inputbar} />
                            </Form.Item>
                        </li>
                        <li>
                            <label htmlFor="mail"><span>Email <span className={Con_style.requiredstar}>*</span></span></label>
                            <input type="email" id="mail" name="user_email" />
                        </li>
                        <li>
                            <label htmlFor="msg"><span>Message</span></label>
                            <textarea></textarea>
                        </li>
                        <li>
                            <input type="submit"/>
                        </li>
                    </ul>
                    </Form>
              </div>
            
        </div>
      </div>

      <Footer />
      </>
  );
}

export default contact;