import React from 'react';
import Head from 'next/head'
import Header from './Header';
import Footer from './Footer';
import Image from 'next/image'
import res_kit from '../styles/res-kitchen.module.css'
function res_kitchen() {
  return (
  <>
          <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

        <main>
          <Header />
          <div className="container mt-5">
          <span className={res_kit.border_top}></span>
            <div className="row">
              <div className="col-lg-8">

                <h3 className={res_kit.menu_head}>Menu for Keeva Indian Kitchen</h3>

                <div className={res_kit.menu_item_box}>
                  <img src="/img/a.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/one.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/two.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/three.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>

                <span className={res_kit.border_bottom}>Tandoor Kebabs</span>

                <div className={res_kit.menu_item_box}>
                  <img src="/img/menu_medium_square.png" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/five.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/four.jpg" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                <div className={res_kit.menu_item_box}>
                  <img src="/img/menu_medium_square.png" alt="" />
                 <div className={res_kit.flex_menu_box}>
                 <span className={res_kit.item_title}>Samosa</span>
                  <span className={res_kit.item_description}>Puff pastry stuffed with potatoes and english peas.
                  <span className={res_kit.item_price}>$55</span>
                  </span>
                  <div className={res_kit.item_icons}>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-star"></i> 53: Reviews
                    </span>
                    <span className={res_kit.item_span_icon}>
                    <i className="fas fa-camera"></i> 5: Photos
                    </span>
                  </div>
                 </div>
                </div>
                
              </div>

              <div className="col-lg-4">
              <span className={res_kit.form_text}>Menu may not be up to date. <a href="">Submit corrections.</a> </span>

              <div className={res_kit.main}>
                <img src="/img/logologo.f87723ea.png" className={res_kit.img_box} alt="" />
                <input type="radio" id="tab-1" className={res_kit.tab_1} name="show" checked />
                <label htmlFor="tab-1" className={res_kit.label}>Delivery</label>
                <input type="radio" id="tab-2" className={res_kit.tab_2} name="show" />
                <label htmlFor="tab-2" className={res_kit.label}>Takeout</label>


                <div className={res_kit.tab}>
                </div>
                
                <div className={res_kit.content}>
                  <div className={res_kit.content_dis}>
                   <div className={res_kit.delive_address}>
                     <span className={res_kit.address}>Delivery Address</span>
                     <input type="text" className={res_kit.check} placeholder='Enter Your Delivery Address'/>
                     <button className={res_kit.str_order}>Start Order</button>
                   </div>
                  </div>
                  <div className={res_kit.content_dis}>
                    <div className={res_kit.delive_address}>
                      <button className={res_kit.str_order}>Start Order</button>
                    </div>
                  </div>
                </div>
              </div>

              <div className={res_kit.popular_section}>
                <span className={res_kit.pop_head}>What Popular Here?</span>

                <div className={res_kit.pop_items}>
                  <img src="/img/ri8one.jpg" alt="" />
                  <div className={res_kit.pop_content}>
                    <span className={res_kit.pop_title}>Chicken Tikka Masala</span>
                    <span className={res_kit.pop_description}>Joise B .
                     <span className={res_kit.inner_text}>Seriously some of the best Indian food in sf!! 
                        I&#39;ve been disappointed by some of the other local</span>
                     </span>
                  </div>
                </div>

                <div className={res_kit.pop_items}>
                  <img src="/img/ri8two.jpg" alt="" />
                  <div className={res_kit.pop_content}>
                    <span className={res_kit.pop_title}>Chicken Tikka Masala</span>
                    <span className={res_kit.pop_description}>Joise B .
                     <span className={res_kit.inner_text}>Seriously some of the best Indian food in sf!! 
                        I&#39;ve been disappointed by some of the other local</span>
                     </span>
                  </div>
                </div>

                <div className={res_kit.pop_items}>
                  <img src="/img/ri83.jpg" alt="" />
                  <div className={res_kit.pop_content}>
                    <span className={res_kit.pop_title}>Chicken Tikka Masala</span>
                    <span className={res_kit.pop_description}>Joise B .
                     <span className={res_kit.inner_text}>Seriously some of the best Indian food in sf!! 
                        I&#39;ve been disappointed by some of the other local</span>
                     </span>
                  </div>
                </div>

                <div className={res_kit.pop_items}>
                  <img src="/img/ri84.jpg" alt="" />
                  <div className={res_kit.pop_content}>
                    <span className={res_kit.pop_title}>Chicken Tikka Masala</span>
                    <span className={res_kit.pop_description}>Joise B .
                     <span className={res_kit.inner_text}>Seriously some of the best Indian food in sf!! 
                        I&#39;ve been disappointed by some of the other local</span>
                     </span>
                  </div>
                </div>

                <div className={res_kit.pop_items}>
                  <img src="/img/ri85.jpg" alt="" />
                  <div className={res_kit.pop_content}>
                    <span className={res_kit.pop_title}>Chicken Tikka Masala</span>
                    <span className={res_kit.pop_description}>Joise B .
                     <span className={res_kit.inner_text}>Seriously some of the best Indian food in sf!! 
                        I&#39;ve been disappointed by some of the other local</span>
                     </span>
                  </div>
                </div>
                
              </div>
              </div>
            </div>
          </div>
          <Footer />
        </main>
  </>
  );
}

export default res_kitchen;
