
/* eslint-disable react/jsx-key */
/* eslint-disable react-hooks/rules-of-hooks */

import Head from 'next/head'
import Footer from './Footer';
import Header from './Header';
import React,{useState, useEffect} from 'react'
import resstyle from '../styles/resbox.module.css';
import { useSelector } from 'react-redux';
import { selectOpenResturant } from '.././components/features/ResSlice';
import SimpleMap from './simpleMap';
import { GoogleApiWrapper, Map } from 'google-maps-react';
import data from './data.json';
import { Rate } from 'antd';
import Question from './Question'
import ResFood from './ResFood'
import { addDoc, collection, serverTimestamp, updateDoc,doc, onSnapshot, query,where } from 'firebase/firestore';
import { db,storage } from '../firebase';
import FoodItems from './FoodItems';
import FoodList from './FoodList'
function resbox() {
    const [ review,setReview ] = useState("");
    const [ question,setQuestion ] = useState("");
    const [food, setFood] = useState("");
    const handleSubmit = async (e) => {
       
        try {
        const docRef=  await addDoc(collection(db, 'review'), {
         review:review,

          })
       
        alert("Review submited")
        } catch (err) {
          alert(err)
        }
    }
    const handleSelect = async value => {
        const results = await geocodeByAddress(value)
        const ll = await getLatLng(results[0])
        console.log("Abdul",ll);

    }
    
    useEffect(() => {
      getQuestion();
      getFood();
    }, [])
    const getFood = () => {
        onSnapshot(
    query(collection(db,"food")),  (snapshot)=>{setFood(snapshot.docs)
    console.log("getFood", snapshot.docs);
    }
    
    )
    
      }
  const getQuestion = () => {
    onSnapshot(
query(collection(db,"Question")),  (snapshot)=>{setQuestion(snapshot.docs)
console.log(snapshot.docs);
}

)

  }
  const renderQuestion = () => {
    if (question && question?.length) {
    return question.map((item, index) => {
      return <Question
        obj={item}
      />
      
    })
    }
  }
  const getResturants = () => {
    onSnapshot(
      query(collection(db,"food"),  where("id", "==", selectResturant.id)), (snapshot)=>{setFood(snapshot.docs)
      console.log(snapshot.docs);
      })
  };
  useEffect(() => {
    getResturants();

  }, [])
  const renderFood = () => {
    if (food.length > 0) {
      console.log("food", food);
      async function trying(url) {
        let image = await url.then(async (url) => { return url })
        console.log('image', image)
        return image.toString()
      }
      // console.log('state', img)
      return food.map((item, index) => {
        return <ResFood
          obj={item}
        />
        
      })
    }
  };
  
    const selectResturant = useSelector(selectOpenResturant)

    return (
        <>

            <Head>
                <title>Food Port</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
                <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
            </Head>

            <Header />

            <section style={{backgroundImage:`url(${selectResturant?.data().image})`}} className={`${resstyle.restaurent_box_banner} ${resstyle.banner_effect}`}>
                <div className="container flexis">
                    <div className="row">
                        <div className="col-lg-8 col-sm-12">
                        {/* {data.resboxbanner.map((post,key) =>{
                             return( */}

                            <div className={resstyle.text_section_res_box}>
                                <span className={resstyle.restaurent_head}>{selectResturant?.data().resName}</span>
                                <br />
                               {/* <span > <Rate disabled defaultValue={2}  /></span> */}

                                <span className={`${resstyle.star} ${resstyle.one}`}>★</span> <span className={`${resstyle.star} ${resstyle.two}`}>★</span>
                                <span className={`${resstyle.star} ${resstyle.three}`}>★</span> <span className={`${resstyle.star} ${resstyle.four}`}>★</span>
                                <span className={`${resstyle.star} ${resstyle.five}`}>★</span>
                                {/* <span className={resstyle.restaurants_reviews}>5</span> */}
                                <br />
                                <br />
                                <div className={resstyle.restaurent_timing}>
                                    <i className="fas fa-check-circle"></i>
                                    <span>{selectResturant?.data().address}</span>
                                    {/* <span className={resstyle.dollars}>bars</span>
                                    <a className={resstyle.bar_links}>bars1</a>
                                    <a className={resstyle.bar_links}>bars2</a>
                                    <a className={resstyle.eidt_btn_res}>bars3</a> */}
                                </div>
                                <br />

                                <span className={resstyle.time}>Open</span>
                                <span className={resstyle.time}>11:30 AM - 10:00 PM</span>

                            </div>
                               {/* )
                            })} */}
                        </div>
                    </div>
                </div>
            </section>

            <div className="container mt-3">
                <div className="row">
                    <div className="col-lg-8">
                        <div className={resstyle.button_group}>
                            <button><i className="fas fa-star-half-alt"></i> Write a Review</button>
                            <button><i className="fas fa-share"></i> Share</button>
                            <button><i className="far fa-bookmark"></i> Save</button>
                            <br />
                            <br />
                            <hr />
                        </div>

                        <div className={resstyle.res_menu_itembox}>
                            <span>Menu</span>
                            <br />
                            <br />
                            <span>Most mentioned dishes
                                <a className={resstyle.float_right}>
                                    View Full Menu
                                </a>
                            </span>
                            <div className={resstyle.scrolling_res_box}>
                            {/* {data.scrollingResbox.map((post,key) =>{
                             return( */}
                            {renderFood()}

                         
                                   {/* )
                                })} */}
                                {/* <div className={resstyle.inner_item_div}>
                                    <img src="img/carlitos-barbecue-tacqueria-catering-scaled.jpg" alt="" />
                                    <h5>Cucumber Salad</h5>
                                    <p>1 : Photo</p>
                                    <p>5 : Review</p>
                                </div>
                                <div className={resstyle.inner_item_div}>
                                    <img src="img/carlitos-barbecue-tacqueria-catering-scaled.jpg" alt="" />
                                    <h5>Honey Sesame Tofu</h5>
                                    <p>1 : Photo</p>
                                    <p>5 : Review</p>
                                </div>

                                <div className={resstyle.inner_item_div}>
                                    <img src="img/carlitos-barbecue-tacqueria-catering-scaled.jpg" alt="" />
                                    <h5>Orange Chicken</h5>
                                    <p>1 : Photo</p>
                                    <p>5 : Review</p>
                                </div>

                                <div className={resstyle.inner_item_div}>
                                    <img src="img/carlitos-barbecue-tacqueria-catering-scaled.jpg" alt="" />
                                    <h5>Chow Mein</h5>
                                    <p>1 : Photo</p>
                                    <p>5 : Review</p>
                                </div> */}
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-4 mt-1">
                    {/* {data.contact.map((post,key) =>{
                             return( */}

                        <div  className={resstyle.get_direction_box}>
                            <span className={resstyle.span_one}>
                                {selectResturant?.data().user}
                                <i className="fas fa-retweet"></i>
                            </span>

                            <hr />
                            <br />

                            <span className={resstyle.span_one}>{selectResturant?.data().phone}
                                <i className="fas fa-phone-alt"></i>
                            </span>

                            <hr />
                            <br />

                            <span className={resstyle.span_one}>
                                <h6 className={resstyle.span_three_head}>address</h6>
                                {selectResturant?.data().address}
                                <i className="fas fa-directions"></i>
                            </span>

                            <hr />

                            <span className={resstyle.span_one}>
                                Message the Business<i className="far fa-comment-dots"></i>
                            </span>

                        </div>
                           {/* )
                        })} */}
                    </div>
                </div>
                <hr />
                <div className="row">
                    <div className="col-lg-4 mt-5">
                    {data.location.map((post,key) =>{
                             return(
                        <div key={key} className={resstyle.restaurent_small_map}>
                            <h5 className={resstyle.map_head}>{post.title}</h5>
                            <div className={resstyle.restaurent_locat_map}>
                                {/* <iframe className={resstyle.map_layout}
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2822.7806761080233!2d-93.29138368446431!3d44.96844997909819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x52b32b6ee2c87c91%3A0xc20dff2748d2bd92!2sWalker+Art+Center!5e0!3m2!1sen!2sus!4v1514524647889">
                                        
                                </iframe> */}
                                 <SimpleMap className="map_layout" lat={selectResturant?.data().lat} lng={selectResturant?.data().lng}/>
                            </div>

                            <div className={resstyle.liwidth}>
                                <li>{selectResturant?.data().address}   </li>
                          
                            </div>
                            <div className={resstyle.liwidth}>
                                <a>Get Directions</a>
                                
                            </div>
                        </div>
                          )
                        })}
                    </div>
                    <div className="col-lg-6">
                    
                        <div className={`${resstyle.bars_restaurent_timing} ${resstyle.table_margin}`}>
                        {/* {data.schedule.map((post,key) =>{
                             return( */}
                            <table  id={resstyle.timing_info}>
                                <tbody>
                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Mon {selectResturant?.data().montime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow" >
                                        <th className="" scope="col">
                                            <p className="">Fri {selectResturant?.data().Fritime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Fri {selectResturant?.data().Fritime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Fri {selectResturant?.data().Fritime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Fri {selectResturant?.data().Fritime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Fri {selectResturant?.data().Fritime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                    <tr className="tablerow">
                                        <th className="" scope="col">
                                            <p className="">Sunday {selectResturant?.data().Suntime}</p>
                                        </th>
                                        <td className="">
                                            <ul className="">
                                                <li className="">
                                                    <p className=""></p>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            {/* )
                        })} */}
                            <ul className="">
                                <li className="">
                                    <p className={resstyle.para_bus}><i className="fas fa-pencil-alt"></i> Edit Business Info</p>
                                </li>
                            </ul>
                             
                        </div>
                         
                    </div>
                </div>
                <div className="row">
                {/* {data.Business.map((post,key) =>{
                             return( */}
                    <div  className="col-lg-8 mt-5">
                      
                        <div  className={resstyle.business_profile}>
                            <img src="img/carlitos-barbecue-tacqueria-catering-scaled.jpg" alt="" />
                            <h5 className={resstyle.about_business}>About the Business
                                <br />
                                <span>{selectResturant?.data().resName}</span>
                            </h5>
                        </div>
                        <div className={resstyle.about_para}>
                            <p>
                            {selectResturant?.data().About}
                            </p>
                            <button className="mt-3">Read More</button>
                        </div>
           
                    </div>
                         {/* )
                        })} */}
                


                </div>
                <hr />
                <div className="row">
                    
                {data.ask.map((post,key) =>{
                             return(
                    <div key={key} className="col-lg-8 mt-5">
                        <div className={resstyle.question_box}>

                            <h5 className={resstyle.ques_head} >
                              {post.title}
                                <span className={resstyle.ask_ques}>Ask a question <i className="fas fa-plus"></i></span>
                            </h5>
                            <div className="form-group mt-5">
                                <textarea className="form-control " type="text" placeholder="" value={question} onChange={(e) => setQuestion(e.target.value)} />
                            </div>
                        <button className="btn signin mt-3" type='submit'  value={review}  onClick={(e) => handleSubmit(e.target.value)}>Submit</button>
                           
                            <h6 className="mt-4">Q :
                                <span className={resstyle.question}>
                                   {post.content}
                                </span>
                            </h6>

                            <h6 className="mt-4">A :
                                <span className={resstyle.answare}>
                                   {post.content1}
                                </span>
                            </h6>
                     
                        </div>

                        <div className="row">
                            <div className="col-lg-7 mt-5">
                                <div className={resstyle.write_reviews_sec}>
                                    <h5 className={resstyle.reviews_head}>Recommended Reviews</h5>
                                    <br />
                                    <div className={resstyle.reviews_sec_box}>
                                        <img src="user-icon.png" alt="" />
                                        <h5 className={resstyle.reviews_info}>User Name
                                            <br />
                                            <span className={resstyle.user_locate}>Location</span>
                                        </h5>
                                        <div className={resstyle.ratingstar}>
                                            <i className="fas fa-star"></i>
                                            <i className="fas fa-star"></i>
                                            <i className="fas fa-star"></i>
                                            <i className="fas fa-star"></i>
                                            <i className="fas fa-star"></i>
                                            <br />
                                            <button className={resstyle.re_btn}>Write a Review</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                     )
                    })}
            

                </div>
            </div>
            <Footer />
        </>
    );
}

export default resbox;