import React,{useState} from 'react'
import form_style from '../styles/form.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useDispatch } from 'react-redux';
import { auth } from '../firebase'
import { login, logout,} from '.././components/features/UserSlice';
import { createUserWithEmailAndPassword } from 'firebase/auth'
export default function Sign_Up() {
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const dispatch = useDispatch();
   
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

        <main>
        <div className={form_style.form_img}>
            <div className={form_style.main_from}>
                <div className={form_style.upper_div}></div>    
            </div>
   
          <form action="">
          <span className={form_style.center_logo}> <img src="/img/logologo.f87723ea.png" alt="" className={form_style.form_logo}/></span>
            <div className="row justify-content-center" id={form_style.form_row}>
                <div className="col-lg-10">
                    <h3 className="text-center"> Sign Up</h3>
                    <div className={form_style.icons_group}>
                        <img src="/img/signin.png" alt="" />
                        <input type="text" className="form-control" name="" id="" placeholder="Enter Your Name" />
                    </div>
                    <div className={form_style.icons_group}>
                        <img src="/img/signin.png" alt="" />
                        <input type="email" className="form-control"  onChange={(e) => setEmail(e.target.value)} placeholder="Enter Your Email Address" />
                    </div>
                    <div className={`${form_style.icons_group}`}>
                        <img src="/img/password.png" alt="" />
                        <input type="text" className="form-control" onChange={(e) => setPassword(e.target.value)} placeholder="Enter Your Password" />
                    </div>
                    <br />
                    <div className={`${form_style.flex_div}`}>
                        <div className={`${form_style.form_group}`}>
                            <input type="checkbox" id='Resturent' value='Resturent Owner' />
                            <label htmlFor="Resturent">Resturent Owner</label>
                        </div>
                        <div className={`${form_style.form_group}`}>
                            <input type="checkbox" id='as_a_user' value='User' />
                            <label htmlFor="as_a_user">As a User</label>
                        </div>
                    </div>
                    <button className={form_style.form_btns}>LOGIN</button> 
                    <br />
                    <div className={form_style.btns_div}>Not a Member?  
                        <button className={form_style.form_btns} ><Link href='/'>Register Now</Link></button>
                    </div>
                </div>
            </div>
       </form>
        </div>
        </main>
    </>
  )
}
