
import React from 'react';
import Head from 'next/head'
import Footer from './Footer';
import Header from './Header';
import Sidebar from './user_sidebar';
function your_orders() {
  return(
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

        <main>
        <Header />
        <Sidebar />

        <div className="container">
            <div className="row justify-content-center mt-5">
                <div className="col-md-3 col-sm-6 lg_own">
                    <div className="serviceBox">
                        <div className="service-content">
                            <div className="service-icon">
                                <span><i className="fas fa-sort-alpha-up"></i></span>
                            </div>
                            <h3 className="title">Your <span>Orders</span></h3>
                            <p className="description">5025</p>
                        </div>
                    </div>
                </div>
                <div className="col-md-3 col-sm-6 lg_own">
                    <div className="serviceBox green">
                        <div className="service-content">
                            <div className="service-icon">
                                <span><i className="fas fa-bookmark"></i></span>
                            </div>
                            <h3 className="title">Your <span>Favourite</span></h3>
                            <p className="description">858233</p>
                        </div>
                    </div>
                </div>
                <div className="col-md-3 col-sm-6 lg_own">
                    <div className="serviceBox blue">
                        <div className="service-content">
                            <div className="service-icon">
                                <span><i className="fas fa-shield-alt"></i></span>
                            </div>
                            <h3 className="title">Your <span>Rewards</span></h3>
                            <p className="description">858236</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div className="container">
            <div className="row">
                <div className="col-md-12">
                    <div className="panel">
                        <div className="panel-heading">
                            <div className="row">
                                <div className="col col-xs-8">
                                    <h4 className="title">RECENT ORDERS</h4>
                                </div>
                            </div>
                        </div>
                        
                        <div className="panel-body table-responsive">
                            <table className="table table-hover">
                                <thead>
                                    <tr className="active">
                                        <th>ORDER ID</th>
                                        <th>TRANSACTION ID</th>
                                        <th>DATE</th>
                                        <th>AMOUNT</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>#8582</td>
                                        <td>52</td>
                                        <td>12 / 5 / 2022</td>
                                        <td>$700</td>
                                    </tr>
                                    <tr>
                                        <td>#8582</td>
                                        <td>52</td>
                                        <td>12 / 5 / 2022</td>
                                        <td>$700</td>
                                    </tr>
                                    <tr>
                                        <td>#8582</td>
                                        <td>52</td>
                                        <td>12 / 5 / 2022</td>
                                        <td>$700</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>

       
      <Footer />
      </main>
      </>
  );
}

export default your_orders;
